name: build
on: push
jobs:

  ros1:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:melodic-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update && sudo apt install \
          git wget \
          python-rosdep \
          python-catkin-tools \
          python3-vcstool \
          python3-colcon-common-extensions \
          python3-colcon-mixin \
          maven default-jdk -y
    - name: workspace
      shell: bash
      run: |
        mkdir -p /home/ros1_ws/src
        cd /home/ros1_ws
        wget https://raw.githubusercontent.com/osrf/free_fleet/${GITHUB_REF:11}/free_fleet_ros1.repos
        vcs import src < free_fleet_ros1.repos
    - name: checkout
      shell: bash
      run: |
        cd /home/ros1_ws/src/free_fleet
        git checkout "${GITHUB_REF:11}"
    - name: rosdeps
      shell: bash
      run: |
        cd /home/ros1_ws
        rosdep update
        rosdep install --from-paths src --ignore-src -y -r --skip-keys="rmf_fleet_msgs ament_lint_common rclpy rclcpp rosidl_default_generators ament_cmake builtin_interfaces"
    - name: build
      shell: bash
      run: |
        cd /home/ros1_ws
        source /opt/ros/melodic/setup.bash
        catkin config --blacklist free_fleet_server_ros2 free_fleet_examples_ros2
        catkin build

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update && sudo apt install \
          git wget \
          python-rosdep \
          python-catkin-tools \
          python3-vcstool \
          python3-colcon-common-extensions \
          python3-colcon-mixin \
          maven default-jdk -y
    - name: workspace
      shell: bash
      run: |
        mkdir -p /home/ros2_ws/src
        cd /home/ros2_ws
        wget https://raw.githubusercontent.com/osrf/free_fleet/${GITHUB_REF:11}/free_fleet_ros2.repos
        vcs import src < free_fleet_ros2.repos
    - name: checkout
      shell: bash
      run: |
        cd /home/ros2_ws/src/free_fleet
        git checkout "${GITHUB_REF:11}"
    - name: rosdeps
      shell: bash
      run: |
        cd /home/ros2_ws
        rosdep update
        rosdep install --from-paths src --ignore-src -y -r --skip-keys="actionlib tf roscpp rviz catkin map_server turtlebot3_navigation turtlebot3_bringup turtlebot3_gazebo"
    - name: build
      shell: bash
      run: |
        cd /home/ros2_ws
        source /opt/ros/eloquent/setup.bash
        colcon build
