name: daily
on:
  schedule:
    - cron: '0 * * * *'
jobs:

  ros1:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:melodic-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update && sudo apt install \
          git cmake wget \
          python3-vcstool \
          python-catkin-tools \
          libyaml-cpp-dev -y
        sudo apt install \
          ros-melodic-move-base-msgs \
          ros-melodic-tf2 \
          ros-melodic-tf2-ros \
          ros-melodic-tf2-geometry-msgs \
          ros-melodic-actionlib \
          ros-melodic-sensor-msgs -y
    - name: workspace
      shell: bash
      run: |
        mkdir -p /home/ros1_ws/src
        cd /home/ros1_ws
        wget https://raw.githubusercontent.com/osrf/free_fleet/${GITHUB_REF:11}/free_fleet_ros1.repos
        vcs import src < free_fleet_ros1.repos
    - name: checkout
      shell: bash
      run: |
        cd /home/ros1_ws/src/free_fleet
        git checkout "${GITHUB_REF:11}"
    - name: build
      shell: bash
      run: |
        cd /home/ros1_ws
        source /opt/ros/melodic/setup.bash
        catkin build cyclonedds --cmake-args -DBUILD_IDLC=NO
        catkin build

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update && sudo apt install \
          git cmake wget \
          python3-vcstool \
          libyaml-cpp-dev -y
    - name: workspace
      shell: bash
      run: |
        mkdir -p /home/ros2_ws/src
        cd /home/ros2_ws
        wget https://raw.githubusercontent.com/osrf/free_fleet/${GITHUB_REF:11}/free_fleet_ros2.repos
        vcs import src < free_fleet_ros2.repos
    - name: checkout
      shell: bash
      run: |
        cd /home/ros2_ws/src/free_fleet
        git checkout "${GITHUB_REF:11}"
    - name: build
      shell: bash
      run: |
        cd /home/ros2_ws
        source /opt/ros/eloquent/setup.bash
        colcon build --packages-select cyclonedds --cmake-args -DBUILD_IDLC=NO
        colcon build --packages-up-to free_fleet_server_ros2 free_fleet_examples_ros2

